# Generated by Django 2.1.7 on 2019-04-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='position',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='edad',
        ),
    ]
