version: '3.3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/nginx/docker.nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/snippets:/opt/app/etc/nginx/snippets
      - ./data/static:/opt/app/data/static
      - ./data/logs:/opt/syncroplicity.panacea/data/logs
    ports:
      - 8001:80
    depends_on:
      - django

  django:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./data/logs:/opt/app/data/logs
      - ./data/static:/opt/app/data/static
      - ./data/media:/opt/app/data/media
      - ./env:/opt/app/env
      - ./camerasdjango:/opt/app/camerasdjango
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - ./env/secrets.env
