version: '3.7'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/docker.nginx.conf:/etc/nginx/nginx.conf
      - ./data/static:/opt/app/data/static
      - ./data/logs:/opt/syncroplicity.panacea/data/logs
    ports:
      - 80:80
    depends_on:
      - django

  django:
    build: .
    volumes:
      - ./data/logs:/opt/app/data/logs
      - ./data/static:/opt/app/data/static
      - ./env:/opt/app/env
      - ./camerasdjango:/opt/app/camerasdjango
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data