# Generated by Django 3.0.5 on 2020-09-17 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('detector_type', models.CharField(choices=[('face_recogntion', 'Face recognition')], default='face_recognition', max_length=32)),
                ('url', models.URLField()),
                ('geopoint', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_webcam', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
