# Generated by Django 2.2.6 on 2020-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_auto_20200406_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.URLField(),
        ),
    ]
