# Generated by Django 2.2.6 on 2020-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='web_cam',
            field=models.BooleanField(default=False),
        ),
    ]
