# Generated by Django 2.2.6 on 2020-04-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_web_cam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='model_detector',
            field=models.CharField(choices=[('FR', 'FACE_RECOGNTION')], default='FR', max_length=2),
        ),
    ]
