# Generated by Django 3.0.5 on 2020-04-12 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_auto_20200412_0342'),
        ('face_recognition', '0003_facesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition.Face')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='facerecognitioncamera',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='facerecognitioncamera_reports',
            name='camera',
        ),
        migrations.DeleteModel(
            name='FacesModel',
        ),
        migrations.DeleteModel(
            name='FaceRecognitionCamera',
        ),
        migrations.DeleteModel(
            name='FaceRecognitionCamera_reports',
        ),
    ]
